import { es as compartido } from '@mentiroso/shared';

/**
 * Textos de la web en español. Estructura preparada para i18n:
 * para añadir un idioma se crea otro diccionario con las mismas claves
 * y se selecciona aquí según el ajuste de idioma.
 */
const ES = {
  ...compartido,
  nav: {
    inicio: 'Inicio',
    local: 'Jugar en local',
    online: 'Jugar online',
    comoJugar: 'Cómo jugar',
    packs: 'Packs',
    ajustes: 'Ajustes',
  },
  comunes: {
    continuar: 'Continuar',
    empezar: 'Empezar',
    volver: 'Volver',
    cancelar: 'Cancelar',
    confirmar: 'Confirmar',
    guardar: 'Guardar',
    cerrar: 'Cerrar',
    salir: 'Salir',
    siguiente: 'Siguiente',
    listo: 'Listo',
    jugadores: 'Jugadores',
    ronda: 'Ronda',
    saltar: 'Saltar',
    aleatorio: 'Aleatorio',
    ayuda: 'Ayuda',
    si: 'Sí',
    no: 'No',
  },
  local: {
    titulo: 'Partida local',
    subtitulo: 'Un móvil que pasa de mano en mano',
    anadirJugador: 'Añadir jugador',
    nombrePlaceholder: 'Nombre…',
    minJugadores: 'Añade al menos 3 jugadores',
    presetsTitulo: 'Empezar rápido',
    elegirModo: 'Modo de juego',
    packsTitulo: 'Packs de palabras',
    ajustesTitulo: 'Ajustes de partida',
    empezarPartida: 'Repartir cartas',
    grupoGuardado: 'Se recuerda el último grupo automáticamente',
  },
  reparto: {
    turnoDe: 'Pásale el móvil a',
    instruccion: 'Arrastra tu tarjeta para revelar tu secreto.',
    ocultar: 'Desliza la tarjeta hacia abajo para taparla',
    soloTu: '¡Que nadie más mire la pantalla! 👀',
    entendido: 'Jugador siguiente',
    aJugar: '¡A jugar!',
    veLaCartaPrimero: 'Desliza la carta para ver tu secreto',
    eresElMentiroso: '¡Eres EL MENTIROSO!',
    mentirosoConsejo: 'No conoces la palabra. Escucha, improvisa y que no te pillen.',
    tuPalabra: 'Tu secreto es:',
    categoria: 'Categoría',
    ayudaInicial: 'Empieza por',
    payasoAviso: 'Eres el PAYASO: conoces la palabra, pero solo ganas si te eliminan.',
    compliceAviso: 'Eres el CÓMPLICE. El mentiroso es:',
    videnteAviso: 'Visión del vidente:',
    esRol: 'es',
  },
  pistas: {
    titulo: 'Ronda de pistas',
    empieza: 'empieza.',
    preparate: '¡Prepárate!',
    turnoDe: 'Le toca a',
    daUnaPista: 'Di una palabra relacionada con tu secreto',
    escribePista: 'Escribe tu pista…',
    responde: 'Responde a la pregunta en voz alta',
    hecho: 'Hecho',
    verPistas: 'Pistas hasta ahora',
    pasarAVotacion: 'Ir a votación',
    saltarADebate: 'Terminar pistas',
  },
  debate: {
    titulo: '¡A debatir!',
    subtitulo: '¿Quién no tiene ni idea? Acusad, defended, mentid…',
    irAVotacion: 'Ir a votación',
    masPistas: 'Otra ronda de pistas',
  },
  votacion: {
    titulo: 'Votación',
    subtituloSecreta: 'Pasad el móvil: cada uno vota en secreto',
    subtituloAbierta: 'Votad en voz alta y marcad al eliminado',
    vota: 'vota…',
    confirmarVoto: 'Confirmar voto',
    verResultado: 'Ver resultado',
    eliminar: 'Eliminar',
    nadie: 'Nadie (empate)',
    hanVotado: 'han votado',
    empateRepite: '¡Empate! Se repite la votación',
  },
  revelacion: {
    expuestoEn: 'Expuesto en…',
    eliminado: 'ha sido eliminado',
    nadieEliminado: 'Empate: nadie ha sido eliminado',
    era: 'era…',
    civilInocente: '¡Era inocente!',
    mentirosoPillado: '¡Era el mentiroso!',
    infiltradoPillado: '¡Era el infiltrado!',
    payasoGana: '¡Era el payaso… y eso quería!',
    continuar: 'Continuar',
  },
  adivinanza: {
    titulo: 'Última oportunidad',
    subtitulo: 'te han pillado… pero puedes robar la victoria',
    instruccion: 'Si adivinas el secreto, ganas la partida',
    placeholder: '¿Cuál era el secreto?',
    probar: 'Adivinar',
    rendirse: 'Me rindo',
  },
  resultado: {
    gananCiviles: '¡Ganan los civiles!',
    gananMentirosos: '¡Ganan los mentirosos!',
    ganaPayaso: '¡Gana el payaso!',
    porAdivinanza: 'El mentiroso adivinó el secreto',
    elSecretoEra: 'El secreto era',
    puntos: 'Puntos',
    marcador: 'Marcador',
    otraRonda: 'Otra partida',
    cambiarAjustes: 'Cambiar ajustes',
    rolesDeTodos: 'Los roles',
  },
  ajustesPartida: {
    mentirosos: 'Mentirosos',
    infiltrados: 'Infiltrados',
    auto: 'Auto',
    rondas: 'Rondas de pistas',
    pistasEscritas: 'Pistas escritas en la app',
    votacionSecreta: 'Votación secreta en la app',
    eliminacionProgresiva: 'Eliminación por rondas',
    adivinanzaFinal: 'Adivinanza final del mentiroso',
    robaVictoria: 'Adivinar roba la victoria',
    ayudaMentiroso: 'Pista para el mentiroso',
    ayudaNada: 'Ninguna',
    ayudaCategoria: 'Ve la categoría',
    ayudaInicial: 'Ve la inicial',
    mostrarCategoria: 'Mostrar categoría a todos',
    empate: 'En caso de empate',
    empateRevotar: 'Revotar una vez',
    empateNadie: 'Nadie eliminado',
    tiempoPista: 'Tiempo por pista',
    tiempoDebate: 'Tiempo de debate',
    tiempoVotacion: 'Tiempo de votación',
    sinLimite: 'Sin límite',
    rolesExtra: 'Roles especiales',
    evitarRepetidas: 'Evitar palabras repetidas',
    avanzado: 'Ajustes avanzados',
  },
  online: {
    titulo: 'Jugar online',
    subtitulo: 'Cada uno desde su móvil, estéis donde estéis',
    crearSala: 'Crear sala',
    unirse: 'Unirse',
    codigoPlaceholder: 'Código de sala',
    tuNombre: 'Tu nombre',
    sala: 'Sala',
    compartir: 'Comparte el código o el enlace',
    copiarEnlace: 'Copiar enlace',
    copiado: '¡Copiado!',
    esperandoJugadores: 'Esperando jugadores…',
    anfitrion: 'Anfitrión',
    expulsar: 'Expulsar',
    empezarPartida: 'Empezar partida',
    faltanJugadores: 'Hacen falta al menos 3 jugadores',
    soloAnfitrion: 'Solo el anfitrión puede cambiar los ajustes',
    desconectado: 'Desconectado — reconectando…',
    chat: 'Chat',
    escribeMensaje: 'Escribe un mensaje…',
    enviarPista: 'Enviar pista',
    esperandoTurno: 'Esperando a',
    tuTurno: '¡Tu turno!',
    hasVotado: 'Voto registrado',
    esperandoVotos: 'Esperando al resto…',
    confirmandoVotos: 'Votos confirmados',
    salaNoExiste: 'Esa sala no existe o ya ha terminado',
    verCarta: 'Ver mi carta',
    anfitrionContinua: 'El anfitrión pasa a la siguiente fase',
    volverAlLobby: 'Volver al lobby',
  },
  errores: compartido.errores,
} as const;

export const t = ES;
export type Textos = typeof ES;
